#API TEST

### get all root category
GET http://localhost:3000/category/roots

### delete a category

DELETE http://localhost:3000/category/14

### create a category
POST http://localhost:3000/category
Content-Type: application/json

{
  "name": "言情小说",
  "parent": 20
}