#API TEST

### get all root category
GET http://localhost:3000/category/roots


### get children category
GET http://localhost:3000/category/2/children-tree

### delete a category

DELETE http://localhost:3000/category/14

### create a category
POST http://localhost:3000/category
Content-Type: application/json

{
  "name": "一度",
  "parent": 2
}

### Init DB
POST http://localhost:3000/category/init-db
Content-Type: application/json

### Get Remove node
Get http://localhost:3000/category/remove-root

### udpate a node
PUT http://localhost:3000/category/5
Content-Type: application/json

{
  "parent": 1
}